feature/8051-add-spent-on
renuo/redmine_auto_time_entries pull request #2
Opened 2017-04-26 07:19 UTC by pascalandermatt

2017-04-26 07:20 UTC, pascalandermatt commented
I discussed the solution with @Kjir (and the tests are green)

2017-04-26 08:08 UTC, lukaselmer commented on spec/assigner_spec.rb
> +        a = Assigner.new '92345678: internal weekly meeting : : 2017-04-25T09:02:30+00: 00'
@pascalandermatt if you select a tag int toggle, `: :` will not be in the string. e.g.

`571115323: bla bla bla : Development : 2017-04-26T08:05:00+00: 00`

2017-04-26 08:11 UTC, lukaselmer requested changes
please also make it work if one selects a tag in toggl

2017-04-26 08:11 UTC, lukaselmer commented on spec/assigner_spec.rb
> +        a = Assigner.new '92345678: internal weekly meeting : : 2017-04-25T09:02:30+00: 00'
![image](https://cloud.githubusercontent.com/assets/326935/25424421/96a75fb4-2a68-11e7-9ad3-a4669a9d9e7b.png)

=> just use the last part as date

2017-04-26 08:17 UTC, lukaselmer commented on spec/redmine_adapter_mock.rb
> +  TimeEntryMock = Struct.new(:issue_id, :spent_on, :comments, :activity_id, :hours, :id, :saved) do
why do you add `spent_on` in front? if you add it at the end, you do not need to change any of the mocks below, right?

2017-04-26 08:18 UTC, lukaselmer commented on spec/assigner_spec.rb
> +        a.spent_on.should == Date.new(2017, 4, 25)
please test the spent_on feature separately

2017-04-26 08:18 UTC, lukaselmer commented on spec/assigner_spec.rb
> +    a = Assigner.new '92345678: 741 Bla bla bla : : 2017-04-25T09:02:30+00: 00'
all these do not need to change, right?

2017-04-26 08:18 UTC, lukaselmer commented on spec/assigner_spec.rb
> +
blank line

2017-04-26 08:19 UTC, lukaselmer commented on lib/assigner.rb
> +    self.spent_on = Date.today
this is done automatically, so we do not need to write this

2017-04-26 13:04 UTC, coorasse commented
I'm happy to leave this to you and Lukas. I do not need to place a review. Thanks both of you!

2017-04-27 10:17 UTC, lukaselmer commented
See #3

2017-04-27 10:17 UTC, closed without merging